language: node_js
node_js:
- node
sudo: false
skip_cleanup: true
cache:
  directories:
  - $HOME/.npm
  - $HOME/.yarn-cache
install:
- npm i -g yarn && yarn --ignore-engines
script:
- npm run test
- npm run test:server
deploy:
  provider: heroku
  api_key:
    secure: putkeyhere
  app:
    develop: nameOfApp
