export const FACEBOOK_PLATFORM_NAME = 'facebook'
export const TWITTER_PLATFORM_NAME = 'twitter'
export const SNAPCHAT_PLATFORM_NAME = 'snapchat'
export const PINTEREST_PLATFORM_NAME = 'pinterest'
export const PLATFORM_NAMES = {
  FACEBOOK: FACEBOOK_PLATFORM_NAME,
  TWITTER: TWITTER_PLATFORM_NAME,
  SNAPCHAT: SNAPCHAT_PLATFORM_NAME,
  PINTEREST: PINTEREST_PLATFORM_NAME
}
